### ISSUE TITLE
Rocketchat service segfaults when connection to the server fails

### ISSUE THREAD

**Issue by atighineanu** [containrrr/shoutrrr#71]
By default, **send** is using the formatted hook, like this `"https://%s/hooks/%s/%s", host, tokenA, tokenB`. However, in cases when my 443 port is busy with a different service, and I've set the chat service to use port 5000 or 3000, adding the port into the rawURL - it ends up with an error:
```
Imba-MacBookPro:shoutrrr alexeitighineanu$ go run cli/main.go send --url "rocketchat://shoutrrr@<myhost>:3000/<mytokenA>/<mytokenB>/general" --message "heyheyhey"

[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13869ea]

goroutine 1 [running]:
github.com/containrrr/shoutrrr/pkg/services/rocketchat.(*Service).Send(0xc0000b8980, 0x7ffeefbff721, 0x9, 0xc0000c0088, 0xc0000b8980, 0x0)
        /Users/alexeitighineanu/go/src/github.com/shoutrrr/pkg/services/rocketchat/rocketchat.go:41 +0x2ea
github.com/containrrr/shoutrrr.Send(0x7ffeefbff6a4, 0x72, 0x7ffeefbff721, 0x9, 0x9, 0x0)
        /Users/alexeitighineanu/go/src/github.com/shoutrrr/shoutrrr.go:24 +0xd7
github.com/containrrr/shoutrrr/cli/cmd/send.Run(0x1913580, 0xc0000dce00, 0x0, 0x4)
        /Users/alexeitighineanu/go/src/github.com/shoutrrr/cli/cmd/send/send.go:49 +0x146
github.com/spf13/cobra.(*Command).execute(0x1913580, 0xc0000dcdc0, 0x4, 0x4, 0x1913580, 0xc0000dcdc0)
        /Users/alexeitighineanu/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x19132e0, 0x0, 0x0, 0x0)
        /Users/alexeitighineanu/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x336
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/alexeitighineanu/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
main.main()
        /Users/alexeitighineanu/go/src/github.com/shoutrrr/cli/main.go:9 +0x31
exit status 2
```

First, I've noticed there is no proper check if the posting happened without problems --> pkg/services/rocketchat/rocketchat.go:
```
res, err := http.Post(apiURL, "application/json", bytes.NewReader(json))
	if res.StatusCode != http.StatusOK {
		return fmt.Errorf("failed to send notification to service, response status code %s", res.Status)
	}
```
A PR is coming right away to address the respective issue.

**Comment by piksel** [comment]
This is in a way two issues in one. I renamed the issue to point to the part of it that is an actual bug/error.

The reason for why you are seeing this are (as you have figured out) that Rocketchat doesn't support specifying the port, which is more of a feature request.

**Comment by atighineanu** [comment]
I've opened a separated Feature request for this.
